# Generated by Django 5.0.3 on 2024-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="submitted_ips",
            field=models.TextField(default=""),
        ),
    ]
