# Generated by Django 5.0.3 on 2024-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_choice_submitted_ips"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="submitted_ips",
        ),
    ]
