python ../manage.py sqlmigrate polls 0001


@REM 让我们看看迁移命令会执行哪些 SQL 语句。sqlmigrate 命令接收一个迁移的名称，然后返回对应的 SQL：

@REM BEGIN;
@REM --
@REM -- Create model Question
@REM --
@REM CREATE TABLE "polls_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question_text" varchar(200) NOT NULL, "pub_date" datetime NOT NULL);
@REM --
@REM -- Create model Choice
@REM --
@REM CREATE TABLE "polls_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL, "question_id" bigint NOT NULL REFERENCES "polls_question" ("id") DEFERRABLE INITIALLY DEFERRED);
@REM CREATE INDEX "polls_choice_question_id_c5b4b260" ON "polls_choice" ("question_id");
@REM COMMIT;

@REM -- 开始一个事务
@REM BEGIN;

@REM -- 创建模型 Question
@REM CREATE TABLE "polls_question" (
@REM     "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- 问题的唯一标识符
@REM     "question_text" varchar(200) NOT NULL,  -- 问题的文本描述
@REM     "pub_date" timestamp with time zone NOT NULL -- 问题的发布日期
@REM );

@REM -- 创建模型 Choice
@REM CREATE TABLE "polls_choice" (
@REM     "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- 选项的唯一标识符
@REM     "choice_text" varchar(200) NOT NULL, -- 选项的文本描述
@REM     "votes" integer NOT NULL, -- 选项的票数
@REM     "question_id" bigint NOT NULL -- 外键，指向对应问题的id
@REM );

@REM -- 添加外键约束，确保每个选项都关联到一个问题
@REM ALTER TABLE "polls_choice"
@REM   ADD CONSTRAINT "polls_choice_question_id_c5b4b260_fk_polls_question_id"
@REM     FOREIGN KEY ("question_id")
@REM     REFERENCES "polls_question" ("id")
@REM     DEFERRABLE INITIALLY DEFERRED;

@REM -- 创建用于加速查询的索引
@REM CREATE INDEX "polls_choice_question_id_c5b4b260" ON "polls_choice" ("question_id");

@REM -- 提交事务
@REM COMMIT;
